@startuml
left to right direction

actor Gebruiker
actor Speler
Speler -|> Gebruiker

(Gebruiker registreren) as (Account registreren)
(Inloggen)
(Deck samenstellen)
(Gevecht starten)
(Gevecht uitvoeren)
(Progressie maken)
(Statistieken bekijken)
(Leaderboard bekijken)
(AI programmeren)

Gebruiker --> (Account registreren)
Gebruiker --> (Inloggen)

Speler --> (Deck samenstellen)
Speler --> (Gevecht starten)
Speler --> (Gevecht uitvoeren)
Speler --> (Statistieken bekijken)
Speler --> (Leaderboard bekijken)
Speler --> (Progressie maken)
Speler --> (AI programmeren)

(Gevecht uitvoeren) ..> (Gevecht starten) : <<include>>
(Progressie maken) ..> (Gevecht uitvoeren) : <<extend>>
(AI programmeren) ..> (Gevecht starten) : <<extend>>
@enduml
